version: '3.7'

services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: aspnetcore/sandbox:multi
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"